# 1. BuatlahTensor di bawah ini dengan Python:

In [25]:
np.array([
    [[23,50], [7,12]],
    [[57,67], [99,43]],
    [[75,21], [57,12]],
    [[87,26], [18,84]],
    ])

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

# 2. Lakukan perkalian terhadap matrix berikut:

In [48]:
matrix_A = np.array([[23,50,19], [7,12,109], [57,67,98]])
matrix_B = np.array([[17], [22], [19]])

In [57]:
print(matrix_A)
matrix_A.shape

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


(3, 3)

In [56]:
print(matrix_B)
matrix_B.shape

[[17]
 [22]
 [19]]


(3, 1)

In [62]:
# perkalian matrix seperti perkalian dot product
print(matrix_A@matrix_B)

[[1852]
 [2454]
 [4305]]


# 3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

In [59]:
A = np.array([[23, 50, 19], [7,12,109], [57,67,98]])
print(A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [65]:
# Transpose dari matriks A
print(A.T)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [64]:
# determinan
print(np.linalg.det(A))

131344.0000000002


In [66]:
# inverse
print(np.linalg.inv(A))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
